--
-- @lc app=leetcode.cn id=1179 lang=mysql
--
-- [1179] 重新格式化部门表
--

-- @lc code=start
# Write your MySQL query statement below
SELECT ID,
SUM(CASE WHEN MONTH='JAN' THEN REVENUE END) AS JAN_REVENUE,
SUM(CASE WHEN MONTH='FEB' THEN REVENUE END) AS FEB_REVENUE,
SUM(CASE WHEN MONTH='MAR' THEN REVENUE END) AS MAR_REVENUE,
SUM(CASE WHEN MONTH='APR' THEN REVENUE END) AS APR_REVENUE,
SUM(CASE WHEN MONTH='MAY' THEN REVENUE END) AS MAY_REVENUE,
SUM(CASE WHEN MONTH='JUN' THEN REVENUE END) AS JUN_REVENUE,
SUM(CASE WHEN MONTH='JUL' THEN REVENUE END) AS JUL_REVENUE,
SUM(CASE WHEN MONTH='AUG' THEN REVENUE END) AS AUG_REVENUE,
SUM(CASE WHEN MONTH='SEP' THEN REVENUE END) AS SEP_REVENUE,
SUM(CASE WHEN MONTH='OCT' THEN REVENUE END) AS OCT_REVENUE,
SUM(CASE WHEN MONTH='NOV' THEN REVENUE END) AS NOV_REVENUE,
SUM(CASE WHEN MONTH='DEC' THEN REVENUE END) AS DEC_REVENUE
FROM DEPARTMENT
GROUP BY ID

-- @lc code=end


 +------+---------+-------+ | id | revenue | month | +------+---------+-------+ | | 8000 | Jan | | 1 | 7000 | Feb | | | 6000 | Mar | +------+---------+-------+ | 2 | 9000 | Jan | +------+---------+-------+ | 3 | 10000 | Feb |
